language: php

php:
  - 5.6

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan config:clear
  - php artisan migrate:refresh --seed

script:
  - vendor/bin/phpunit

deploy:
  provider: heroku
  api_key:
    secure: "8028dad9-27b9-492a-83bf-84c2a7288d58"
  app: gentle-dusk-79476
  on: master
  run:
    - php artisan migrate --force